name: Action CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Run my own container action
        uses: ./ # Uses an action in the root directory
        id: my-action
        with:
          who-to-greet: '@wheezy'

        # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.my-action.outputs.time }}"

      - name: Output the answer
        run: echo "The answer is ${{ steps.my-action.outputs.answer}}"

      - name: Test the container
        if: ${{ steps.my-action.outputs.answer != 42 }}
        run: |
            echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
            exit 1